In [2]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("valakhorasani/bank-transaction-dataset-for-fraud-detection")

Warning: Looks like you're using an outdated `kagglehub` version, please consider updating (latest version: 0.3.12)

In [3]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv('bank_transactions_data_2.csv')
df

,TransactionID,AccountID,TransactionAmount,TransactionDate,TransactionType,Location,DeviceID,IP Address,MerchantID,Channel,CustomerAge,CustomerOccupation,TransactionDuration,LoginAttempts,AccountBalance,PreviousTransactionDate
0,TX000001,AC00128,14.09,2023-04-11 16:29:14,Debit,San Diego,D000380,162.198.218.92,M015,ATM,70,Doctor,81,1,5112.21,2024-11-04 08:08:08
1,TX000002,AC00455,376.24,2023-06-27 16:44:19,Debit,Houston,D000051,13.149.61.4,M052,ATM,68,Doctor,141,1,13758.91,2024-11-04 08:09:35
2,TX000003,AC00019,126.29,2023-07-10 18:16:08,Debit,Mesa,D000235,215.97.143.157,M009,Online,19,Student,56,1,1122.35,2024-11-04 08:07:04
3,TX000004,AC00070,184.50,2023-05-05 16:32:11,Debit,Raleigh,D000187,200.13.225.150,M002,Online,26,Student,25,1,8569.06,2024-11-04 08:09:06
4,TX000005,AC00411,13.45,2023-10-16 17:51:24,Credit,Atlanta,D000308,65.164.3.100,M091,Online,26,Student,198,1,7429.40,2024-11-04 08:06:39
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2507,TX002508,AC00297,856.21,2023-04-26 17:09:36,Credit,Colorado Springs,D000625,21.157.41.17,M072,Branch,33,Doctor,109,1,12690.79,2024-11-04 08:11:29
2508,TX002509,AC00322,251.54,2023-03-22 17:36:48,Debit,Tucson,D000410,49.174.157.140,M029,Branch,48,Doctor,177,1,254.75,2024-11-04 08:11:42
2509,TX002510,AC00095,28.63,2023-08-21 17:08:50,Debit,San Diego,D000095,58.1.27.124,M087,Branch,56,Retired,146,1,3382.91,2024-11-04 08:08:39
2510,TX002511,AC00118,185.97,2023-02-24 16:24:46,Debit,Denver,D000634,21.190.11.223,M041,Online,23,Student,19,1,1776.91,2024-11-04 08:12:22
2511,TX002512,AC00009,243.08,2023-02-14 16:21:23,Credit,Jacksonville,D000215,59.127.135.25,M041,Online,24,Student,93,1,131.25,2024-11-04 08:07:49

In [13]:
#df.sort_values(by='AccountID', ascending=True)
#df[df['LoginAttempts'] > 1]
#df.pivot_table(index=['AccountID','TransactionID'], values='TransactionAmount', aggfunc='sum')
#df.sort_values(by='TransactionDate', ascending=False)['TransactionID'] == 'TX000687'

df[df['AccountID'] == 'AC00370'].sort_values(by='TransactionDate', ascending=False)
#df[(df['LoginAttempts'] >= 2)].sort_values(by = 'LoginAttempts', ascending=False)
#df[(df['LoginAttempts'] >= 2)].sort_values(by = 'AccountID', ascending=False)

,TransactionID,AccountID,TransactionAmount,TransactionDate,TransactionType,Location,DeviceID,IP Address,MerchantID,Channel,CustomerAge,CustomerOccupation,TransactionDuration,LoginAttempts,AccountBalance,PreviousTransactionDate
686,TX000687,AC00370,280.92,2024-01-01 18:21:50,Debit,Phoenix,D000320,120.170.93.69,M048,Online,41,Doctor,168,1,5298.85,2024-11-04 08:06:41
849,TX000850,AC00370,194.99,2023-12-01 17:01:30,Debit,Jacksonville,D000442,173.232.121.213,M097,Branch,34,Engineer,91,1,1370.03,2024-11-04 08:07:50
2400,TX002401,AC00370,131.69,2023-10-16 16:22:32,Credit,Denver,D000044,30.229.179.194,M067,Branch,53,Engineer,59,1,2958.43,2024-11-04 08:07:03
625,TX000626,AC00370,821.54,2023-08-22 18:11:16,Credit,Atlanta,D000142,19.111.192.175,M044,Branch,79,Retired,36,1,4040.32,2024-11-04 08:11:57
1501,TX001502,AC00370,417.26,2023-02-27 17:01:24,Credit,New York,D000183,17.36.132.202,M049,Online,32,Doctor,45,1,10442.48,2024-11-04 08:11:53
1964,TX001965,AC00370,78.93,2023-02-17 16:41:31,Debit,Mesa,D000602,211.45.75.44,M099,ATM,38,Doctor,145,1,9916.24,2024-11-04 08:12:17
207,TX000208,AC00370,485.54,2023-02-06 17:46:59,Debit,Houston,D000589,140.212.253.222,M061,ATM,46,Engineer,143,1,6371.51,2024-11-04 08:11:46

In [33]:
df[(df['LoginAttempts'] >= 2)].sort_values(by = 'AccountID', ascending=False).head(15)
#should focus primarily for debit transactions since WHO THE FUCK WOULD CREDIT AN ACCOUNT AND CONSIDER IT FRAUD WAHAH TNGA

,TransactionID,AccountID,TransactionAmount,TransactionDate,TransactionType,Location,DeviceID,IP Address,MerchantID,Channel,CustomerAge,CustomerOccupation,TransactionDuration,LoginAttempts,AccountBalance,PreviousTransactionDate
117,TX000118,AC00498,56.98,2024-01-01 16:34:10,Credit,Oklahoma City,D000256,101.90.40.193,M086,ATM,43,Engineer,122,2,5688.37,2024-11-04 08:07:42
414,TX000415,AC00495,83.50,2023-05-15 18:47:35,Debit,Dallas,D000446,34.92.221.183,M100,Branch,61,Retired,91,5,1749.79,2024-11-04 08:07:22
38,TX000039,AC00478,795.31,2023-10-12 17:07:40,Debit,Mesa,D000077,49.29.37.185,M048,ATM,66,Doctor,90,2,7914.88,2024-11-04 08:11:17
1309,TX001310,AC00470,470.96,2023-03-10 16:22:05,Credit,Indianapolis,D000600,106.244.1.47,M036,Online,69,Doctor,124,2,12991.03,2024-11-04 08:11:10
792,TX000793,AC00468,253.55,2023-01-11 16:56:58,Debit,Jacksonville,D000112,41.82.55.163,M007,ATM,28,Engineer,85,5,2797.26,2024-11-04 08:09:12
2371,TX002372,AC00465,21.23,2023-09-11 16:35:15,Debit,Virginia Beach,D000174,63.191.171.41,M094,ATM,23,Student,103,4,319.18,2024-11-04 08:09:59
551,TX000552,AC00465,106.16,2023-04-14 17:21:48,Debit,Phoenix,D000673,48.89.167.189,M098,ATM,56,Doctor,277,4,7487.79,2024-11-04 08:08:51
1161,TX001162,AC00460,484.30,2023-10-17 17:46:52,Credit,Boston,D000407,93.160.83.196,M026,Online,61,Retired,230,3,7910.30,2024-11-04 08:11:08
547,TX000548,AC00456,97.09,2023-04-10 18:26:56,Debit,Fort Worth,D000164,221.206.44.63,M052,ATM,24,Student,202,4,1579.57,2024-11-04 08:06:33
1659,TX001660,AC00456,53.79,2023-12-05 16:01:44,Credit,Philadelphia,D000199,101.223.82.253,M072,ATM,54,Engineer,137,3,6229.36,2024-11-04 08:07:47
274,TX000275,AC00454,1176.28,2023-12-20 16:08:02,Credit,Kansas City,D000476,50.202.8.53,M074,ATM,54,Engineer,174,5,323.69,2024-11-04 08:11:44
23,TX000024,AC00453,345.84,2023-05-02 18:25:46,Debit,Fort Worth,D000162,191.82.103.198,M083,Online,22,Student,142,3,1402.50,2024-11-04 08:07:04
476,TX000477,AC00442,53.81,2023-10-16 16:55:44,Credit,Raleigh,D000663,34.86.220.205,M079,ATM,55,Engineer,37,2,2564.62,2024-11-04 08:12:05
26,TX000027,AC00441,246.93,2023-04-17 16:37:01,Debit,Miami,D000046,55.154.161.250,M029,ATM,23,Student,158,5,673.35,2024-11-04 08:11:38
2445,TX002446,AC00439,403.01,2023-09-04 17:32:35,Debit,Washington,D000677,223.32.70.156,M029,Online,63,Doctor,286,3,10513.52,2024-11-04 08:09:32