In [1]:
import pandas as pd
from datasets import load_dataset
import matplotlib.pyplot as plt

dataset = load_dataset('lukebarousse/data_jobs')
df = dataset['train'].to_pandas()

df['job_posted_date'] = pd.to_datetime(df['job_posted_date'])

In [7]:
df.pivot_table(values='salary_year_avg',index='job_title_short', aggfunc=['mean', 'median', 'std'])

                                     mean          median             std
                          salary_year_avg salary_year_avg salary_year_avg
job_title_short
Business Analyst             91082.612833         85000.0    32036.098388
Cloud Engineer              111268.453846         90000.0    50514.351080
Data Analyst                 93841.907854         90000.0    34100.108034
Data Engineer               130125.604250        125000.0    42525.929674
Data Scientist              135988.837171        127500.0    52227.832196
Machine Learning Engineer   126774.315972        106415.0    53914.993342
Senior Data Analyst         113911.363665        111175.0    34060.065096
Senior Data Engineer        145840.611624        147500.0    37415.120392
Senior Data Scientist       154206.292996        155500.0    50927.738257
Software Engineer           113393.760054         99150.0    51624.385181

In [32]:
index_to_sort = df[['job_title_short', 'salary_year_avg']][df['job_title_short'] == 'Data Analyst']
index_to_sort.reset_index(inplace=True)
index_to_sort

        job_index job_title_short  salary_year_avg
0               1    Data Analyst              NaN
1              12    Data Analyst              NaN
2              18    Data Analyst              NaN
3              31    Data Analyst              NaN
4              34    Data Analyst              NaN
...           ...             ...              ...
196070     785703    Data Analyst              NaN
196071     785705    Data Analyst              NaN
196072     785715    Data Analyst              NaN
196073     785717    Data Analyst              NaN
196074     785737    Data Analyst              NaN

[196075 rows x 3 columns]

In [33]:
index_to_sort.set_index(keys='job_index', inplace=True)

In [34]:
index_to_sort

          job_title_short  salary_year_avg
job_index
1            Data Analyst              NaN
12           Data Analyst              NaN
18           Data Analyst              NaN
31           Data Analyst              NaN
34           Data Analyst              NaN
...                   ...              ...
785703       Data Analyst              NaN
785705       Data Analyst              NaN
785715       Data Analyst              NaN
785717       Data Analyst              NaN
785737       Data Analyst              NaN

[196075 rows x 2 columns]