In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
pd.set_option('display.max_columns', 100)
sns.set_style('whitegrid')

In [3]:
df = pd.read_csv('mockup_credit_card_excel_1000_rows.csv')
df

# the goal of this case study is to

,customer_id,age,segment,region,tenure_months,credit_limit,avg_monthly_spend,txns_last_3mo,days_past_due,churn_flag,current_balance,utilization_rate,pct_revolve,revolve_balance,delinquent_flag
0,100001,59,Mass,East,1,50000,13278.0,23,0,0,55961.0,1.12,0.48,26861.0,0
1,100002,49,Affluent,West,87,50000,19737.0,21,0,1,61360.0,1.23,0.39,23930.0,0
2,100003,35,Affluent,South,128,120000,7782.0,24,30,1,52927.0,0.44,0.27,14290.0,1
3,100004,63,Mass,North,67,120000,14637.0,19,0,0,24859.0,0.21,0.37,9198.0,0
4,100005,28,Affluent,East,4,120000,20698.0,29,0,0,28070.0,0.23,0.35,9824.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,100996,44,Mass,East,149,50000,19541.0,24,0,0,6862.0,0.14,0.23,1578.0,0
996,100997,29,Mass,South,99,20000,21912.0,23,0,0,5011.0,0.25,0.49,2455.0,0
997,100998,23,Mass,North,76,50000,19656.0,19,0,0,32040.0,0.64,0.27,8651.0,0
998,100999,51,Mass,West,26,50000,9333.0,17,0,0,45242.0,0.90,0.27,12215.0,0
999,101000,60,Starter,West,115,80000,19754.0,20,0,0,2327.0,0.03,0.28,652.0,0

In [4]:
df.query('churn_flag == 1')

,customer_id,age,segment,region,tenure_months,credit_limit,avg_monthly_spend,txns_last_3mo,days_past_due,churn_flag,current_balance,utilization_rate,pct_revolve,revolve_balance,delinquent_flag
1,100002,49,Affluent,West,87,50000,19737.0,21,0,1,61360.0,1.23,0.39,23930.0,0
2,100003,35,Affluent,South,128,120000,7782.0,24,30,1,52927.0,0.44,0.27,14290.0,1
5,100006,41,Starter,North,153,50000,15171.0,24,0,1,11882.0,0.24,0.68,8080.0,0
6,100007,59,Affluent,East,47,80000,17206.0,17,0,1,29890.0,0.37,0.28,8369.0,0
10,100011,31,Mass,East,57,80000,32917.0,17,0,1,21456.0,0.27,0.31,6651.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
921,100922,34,Affluent,South,93,200000,30302.0,15,0,1,28236.0,0.14,0.19,5365.0,0
939,100940,38,Mass,East,101,50000,18242.0,27,0,1,15709.0,0.31,0.29,4556.0,0
941,100942,55,Starter,East,121,20000,15277.0,27,0,1,5534.0,0.28,0.47,2601.0,0
957,100958,45,Mass,West,117,20000,19689.0,21,0,1,19467.0,0.97,0.21,4088.0,0
974,100975,39,Starter,West,1,50000,25329.0,26,0,1,10616.0,0.21,0.34,3609.0,0